### ISSUE TITLE
[BUG] I cant run grpc server

### ISSUE THREAD

**Issue by revilon1991** [spiral/roadrunner-binary#126]
Thank you for your work. I have a problem. Maybe, it isn't a bug, but I seem this kind of issue more matches my problem.

I got the `rr` by documentation, then I ran `rr` but I didn't see that `grpc` server is running.
And my client code can't connect to `grpc` server.
What's wrong?

I tried this code:

```shell
composer require spiral/roadrunner:v2.0 nyholm/psr7
./vendor/bin/rr get-binary
./rr serve
# DEBUG rpc Started RPC service {"address": "tcp://127.0.0.1:6001", "plugins": ["informer", "resetter"]}
```

I expected to see this happen:
```json
{"address": "tcp://127.0.0.1:6001", "plugins": ["informer", "resetter", "grpc"]}
```

Instead, this happened:
```json
{"address": "tcp://127.0.0.1:6001", "plugins": ["informer", "resetter"]}
```

The **version of RR** used: `v2.5.3`

The **operation system** used: `linux`

RR configuration file content:

```yaml
# .rr.yaml
rpc:
  enable: true
  listen: tcp://127.0.0.1:6001

grpc:
  listen: "tcp://:9090"
  proto: "service.proto"
  tls:
    key:  "server.key"
    cert: "server.crt"
  workers:
    command: "php GrpcWorker.php"
    pool:
      numWorkers: 1
```

My worker for `grpc` server:
```php
// GrpcWorker.php
<?php

/**
 * Sample GRPC PHP server.
 */

use Service\EchoInterface;
use Spiral\RoadRunner\GRPC\Server;
use Spiral\RoadRunner\Worker;

require __DIR__ . '/vendor/autoload.php';

$server = new Server(null, [
    'debug' => true,
]);

$server->registerService(EchoInterface::class, new EchoService());

$server->serve(Worker::create());
```

My client code:
```php
<?php

include "vendor/autoload.php";

$client = new \Service\EchoClient(
    'localhost:9090',
    [
        'credentials' => \Grpc\ChannelCredentials::createSsl(file_get_contents("server.crt")),
    ]
);

$result = $client->Ping(
    new \Service\Message()
)->wait();

var_dump($result[1]->code, $result[1]->details);
// int(14)
// string(34) "failed to connect to all addresses"
```

Errortrace, Backtrace or Panictrace:
none
