### ISSUE TITLE
[BUG] Missing plugins: `fileserver` and `http_metrics`

### ISSUE THREAD

**Issue by vladimir-vv** [spiral/roadrunner-binary#142]
Greetings,

I was trying to test new **fileserver** module and **http_metrics** middleware - without any success.

As I can see in roadrunner-plugins code may be need to list them in this file?
```text
internal/container/plugins.go
```

The **version of RR** used: *2.6.2*
Also tried with docker container with the same version of RR
The **operation system** used: *Linux 5.14.18-1-MANJARO x86_64*

RR configuration file content:

```yaml
http:
  address: 0.0.0.0:8060
  middleware: ["headers",  "gzip", "http_metrics"]
  pool:
    num_workers: 2
    max_jobs: 16
  headers:
    response:
      X-Powered-By: "RoadRunner"

  static:
    dir: "public/"
    forbid: [".php"]
    response:
      Cache-Control: "public, max-age=300"

fileserver:
  address: 0.0.0.0:8062
  calculate_etag: true
  weak: false
  serve:
    - prefix: "/public"
      root: "public/"
      max_age: 300
```

Could you please take a look?
