### ISSUE TITLE
[BUG] Have a problem to run RR in China

### ISSUE THREAD

**Issue by Alexei007** [spiral/roadrunner-binary#33]
I tried this code:  

```go
./rr -c .rr.yaml serve
```

I expected to see this happen: *The program is running normally*

Instead, this happened: 
![image](https://user-images.githubusercontent.com/26039956/113378537-dc513e00-93a9-11eb-90cd-709e6524ca0e.png)

The **version of RR** used: *2.0.3*

The **operation system** used: *cenots7*

RR configuration file content:

```yaml
http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 8
    max_jobs: 0
    supervisor:
      # watch_tick defines how often to check the state of the workers (seconds)
      watch_tick: 1s
      # ttl defines maximum time worker is allowed to live (seconds)
      ttl: 0
      # idle_ttl defines maximum duration worker can spend in idle mode after first use. Disabled when 0 (seconds)
      idle_ttl: 10s
      # exec_ttl defines maximum lifetime per job (seconds)
      exec_ttl: 10s
      # max_worker_memory limits memory usage per worker (MB)
      max_worker_memory: 100
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600

server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///var/run/rr-rpc.sock"
  relay: "unix:///var/run/rr-rpc.sock"
  env:
    RR_MODE: http

logs:
  mode: development
  level: debug
  encoding: console
  output: stderr
  err_output: stderr
  channels:
    http:
      mode: development
      level: panic
      encoding: console
      output: stdout

# healthcheck
status:
  address: "0.0.0.0:8090"

reload:
  # sync interval
  interval: 1s
  # global patterns to sync
  patterns: [ ".php" ]
  # list of included for sync services
  plugins:
    http:
      # recursive search for file patterns to add
      recursive: true
      # ignored folders
      ignore: [ "vendor" ]
      # service specific file pattens to sync
      patterns: [ ".php", ".go", ".md" ]
      # directories to sync. If recursive is set to true,
      # recursive sync will be applied only to the directories in `dirs` section
      dirs: [ "." ]
```

**Comment by 48d90782** [comment]
Hey @Alexei007. You have the wrong relay value, it should be in the form of ` unix://file.sock`, in your case - `unix://var/run/rr-rpc.sock`

**Comment by 48d90782** [comment]
I might be wrong because I guess your socket has the path from the root `/var/run/rr-rpc.sock`. Could you also try to run your worker separately, because as I see from the logs, there is an error while RR tries to run your worker.

**Comment by Alexei007** [comment]
> Hey @Alexei007. You have the wrong relay value, it should be in the form of ` unix://file.sock`, in your case - `unix://var/run/rr-rpc.sock`

#### Hello, Valery Piashchynski, Thank you for your reply.

#### It doesn't seem to be a configuration file problem. I test the same code on the local server and the cloud server. The cloud server is running normally, and the local server is running incorrectly.

#### I use exactly the same project, include `. rr.yaml` file.
```yaml
server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///var/run/rr-rpc.sock"
  relay: "unix:///var/run/rr-rpc.sock"

http:
  address: 0.0.0.0:8080
  middleware: ["headers", "static", "gzip"]
  pool:
    max_jobs: 64 # feel free to change this
    supervisor:
      exec_ttl: 60s
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "public"
    forbid: [".php"]
```

![image](https://user-images.githubusercontent.com/26039956/113384944-b6cc3080-93b9-11eb-83e1-2e7a6a83be8a.png)

**Comment by 48d90782** [comment]
@Alexei007 Check the 8080 port in your local env. And try to run worker without RR, not to work with, but to check the problem.

**Comment by 48d90782** [comment]
Also, add these lines to your config:
```yaml
# RoadRunner internal container configuration (docs: https://github.com/spiral/endure).
endure:
  grace_period: 30s
  print_graph: false
  log_level: error
```

**Comment by Alexei007** [comment]
##  Большое спасибо за терпение )

#### No error reported, relevant process can be found, When running
```php
php ./vendor/bin/rr-worker start
```
![image](https://user-images.githubusercontent.com/26039956/113386608-34457000-93bd-11eb-911f-fa2ebbdf9028.png)

---

#### When running the code, port 6061 is normal and port 8080 is unused.
![image](https://user-images.githubusercontent.com/26039956/113386736-72db2a80-93bd-11eb-8158-3cdfc9e0d86c.png)

**Comment by 48d90782** [comment]
Firewall, hm... Do you use a firewall in your local env? If so, could you please try to turn it off and re-run the application (temporary)?

**Comment by Alexei007** [comment]
Let me explain, exactly the same project. The cloud server is running normally (centos8 and Ubuntu). The local server, centos7 system, couldn't work normally. At first, I thought it was a system problem, so I tried to install centos8 to run the code. But it still doesn't work, I can't solve the problem. I would like to use RR + laravel in my new project, but the current situation may not work.

---

### Hope @Taylor Otwell will bring a surprise next Monday.
![image](https://user-images.githubusercontent.com/26039956/113387729-753e8400-93bf-11eb-9557-804a79cfe32a.png)

**Comment by Alexei007** [comment]
> Firewall, hm... Do you use a firewall in your local env? If so, could you please try to turn it off and re-run the application (temporary)?

### It's not a firewall problem, the port is open, and I'm running locally.

**Comment by 48d90782** [comment]
As I see from the error log, that by some reason, RR can't allocate a worker at your local system. This is definitely some local system issue. Might be some outdated package or something else. If you paste here the steps on how to reproduce your issue with the *.php worker I'll try to help you.

**Comment by tarampampam** [comment]
Hi @Alexei007! Could you please try to change relay from `unix:///var/run/rr-rpc.sock` to `unix:///tmp/rr-rpc.sock` or `tcp://127.0.0.1:6001` (any unused port)?

**Comment by Alexei007** [comment]
### Many thanks ) You are so handsome )

#### There is a great possibility that there are some outdated packages, Because there are some restrictions on the Internet in China. And I saw in China's technology forum that many developers couldn't run RR normally and didn't find a solution. 

#### But the question now is how to find out that outdated packages.

**Comment by Alexei007** [comment]
> Hi @Alexei007! Could you please try to change relay from `unix:///var/run/rr-rpc.sock` to `unix:///tmp/rr-rpc.sock` or `tcp://127.0.0.1:6001` (any unused port)?

@tarampampam 

#### Thanks for your comment, I tried, That should not be the problem. 

#### This project can run normally on the cloud server.

```yaml
server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///tmp/rr-rpc.sock"
  relay: "unix:///tmp/rr-rpc.sock"

http:
  address: 0.0.0.0:8080
  middleware: ["headers", "static", "gzip"]
  pool:
    max_jobs: 64 # feel free to change this
    supervisor:
      exec_ttl: 60s
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "public"
    forbid: [".php"]
```
